//Auth Types
export const LOAD = "LOAD";

export const REGISTER_MSG = "REGISTER_MSG";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const FORGET_MSG = "FORGET_MSG";
export const FORGET_SUCCESS = "FORGET_SUCCESS";
export const FORGET_FAIL = "FORGET_FAIL";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAIL = "RESET_FAIL";
export const SET_AUTH_VERIFICATION = "SET_AUTH_VERIFICATION";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED_DATA = "USER_LOADED_DATA";
export const AUTH_ERROR_DATA = "AUTH_ERROR_DATA";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const ERR_USERS = "ERR_USERS";

export const LOGOUT = "LOGOUT";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERR = "UPDATE_PASSWORD_ERR";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERR = "UPDATE_PROFILE_ERR";

export const IS_EMAIL_AUTH_ON_SUCCESS = "IS_EMAIL_AUTH_ON_SUCCESS";
export const IS_EMAIL_AUTH_ON_ERR = "IS_EMAIL_AUTH_ON_ERR";

export const IS_GOOGLE_AUTH_ON_SUCCESS = "IS_GOOGLE_AUTH_ON_SUCCESS";
export const IS_GOOGLE_AUTH_ON_ERR = "IS_GOOGLE_AUTH_ON_ERR";

export const IS_SMS_AUTH_ON_SUCCESS = "IS_SMS_AUTH_ON_SUCCESS";
export const IS_SMS_AUTH_ON_ERR = "IS_SMS_AUTH_ON_ERR";

//Dashboard Types

export const GET_SUBSCRIPTION_SUCCESS = "GET_SUBSCRIPTION_SUCCESS";
export const GET_SUBSCRIPTION_ERR = "GET_SUBSCRIPTION_ERR";

export const GET_ONGOING_ITO_SERIES_SUCCESS = "GET_ONGOING_ITO_SERIES_SUCCESS";
export const GET_ONGOING_ITO_SERIES_ERR = "GET_ONGOING_ITO_SERIES_ERR";

export const GET_USER_TOKEN_SUCCESS = "GET_USER_TOKEN_SUCCESS";
export const GET_USER_TOKEN_ERR = "GET_ONGOING_ITO_SERIES_ERR";
export const GET_AVAILABLE_GRAPH = "GET_AVAILABLE_GRAPH";

//User Management Types

//Wallet Types
export const GET_TOKEN_LIST_SUCCESS = "GET_TOKEN_LIST_SUCCESS";
export const GET_TOKEN_LIST_ERR = "GET_TOKEN_LIST_ERR";

export const GET_WALLET_DETAILS_SUCCESS = "GET_WALLET_DETAILS_SUCCESS";
export const GET_WALLET_DETAILS_ERR = "GET_WALLET_DETAILS_ERR";

export const GET_FIAT_TRANSACTION_DETAILS_SUCCESS =
  "GET_FIAT_TRANSACTION_DETAILS_SUCCESS";
export const GET_FIAT_TRANSACTION_DETAILS_ERR =
  "GET_FIAT_TRANSACTION_DETAILS_ERR";

export const DEPOSIT_PAYMENT_SUCCESS = "DEPOSIT_PAYMENT_SUCCESS";
export const DEPOSIT_PAYMENT_ERR = "DEPOSIT_PAYMENT_ERR";

export const TRANSFER_TOKEN_SUCCESS = "TRANSFER_TOKEN_SUCCESS";
export const TRANSFER_TOKEN_ERR = "TRANSFER_TOKEN_ERR";
export const DEPOSIT_FIAT_SUCCESS = "DEPOSIT_FIAT_SUCCESS";
export const DEPOSIT_FIAT_ERR = "DEPOSIT_FIAT_ERR";

export const GET_TOKEN_TRANSACTIONS_SUCCESS = "GET_TOKEN_TRANSACTIONS_SUCCESS";
export const GET_TOKEN_TRANSACTIONS_ERR = "GET_TOKEN_TRANSACTIONS_ERR";

export const PAYPAL_PAYMENT_SUCCESS_SUCCESS = "PAYPAL_PAYMENT_SUCCESS_SUCCESS";
export const PAYPAL_PAYMENT_SUCCESS_ERR = "PAYPAL_PAYMENT_SUCCESS_ERR";

export const PAYPAL_PAYMENT_CANCEL_SUCCESS = "PAYPAL_PAYMENT_CANCEL_SUCCESS";
export const PAYPAL_PAYMENT_CANCEL_ERR = "PAYPAL_PAYMENT_CANCEL_ERR";
export const REQUEST_WITHDRAW = "REQUEST_WITHDRAW";
export const TOKEN_LIST = "GET_TOKEN_LIST";
export const GET_WITHDRAW_LIST = "GET_WITHDRAW_LIST";
export const GET_TOKENS = "GET_TOKENS";
export const GET_BANK_DETAILS = "GET_BANK_DETAILS";

//Kyc Management Types
export const ADD_KYC_SUCCESS = "ADD_KYC_SUCCESS";
export const ADD_KYC_ERR = "ADD_KYC_ERR";
export const GET_KYC_SUCCESS = "GET_KYC_SUCCESS";
export const GET_KYC_ERR = "GET_KYC_ERR";

//Exhange Types
export const GET_TRADEABLE_TOKENS_SUCCESS = "GET_TRADEABLE_TOKENS_SUCCESS";
export const GET_TRADEABLE_TOKENS_ERR = "GET_TRADEABLE_TOKENS_ERR";
export const GET_NON_TRADEABLE_TOKENS_SUCCESS =
  "GET_NON_TRADEABLE_TOKENS_SUCCESS";
export const GET_NON_TRADEABLE_TOKENS_ERR = "GET_NON_TRADEABLE_TOKENS_ERR";
export const GET_ONGOING_SERIES_SUCCESS = "GET_ONGOING_SERIES_SUCCESS";
export const GET_ONGOING_SERIES_ERR = "GET_ONGOING_SERIES_ERR";
export const GET_TOKEN_DETAIL_SUCCESS = "GET_TOKEN_DETAIL_SUCCESS";
export const GET_TOKEN_DETAIL_ERR = "GET_TOKEN_DETAIL_ERR";
export const CREATE_ORDER = "CREATE_ORDER";
export const GET_EXHANGE_ORDER = "GET_EXCHANGE_ORDER";

export const TOKEN_SELECTED_STATUS = "TOKEN_SELECTED_STATUS";
export const SERIES_SELECTED_STATUS = "SERIES_SELECTED_STATUS";
export const BUY_REQUEST_SERIES_SELECTED = "BUY_REQUEST_SERIES_SELECTED";
export const BUY_REQUEST_TOKEN_STATUS = "BUY_REQUEST_TOKEN_STATUS";

export const CREATE_EXCHANGE_ORDER_SUCCESS = "CREATE_EXCHANGE_ORDER_SUCCESS";
export const CREATE_EXCHANGE_ORDER_ERR = "CREATE_EXCHANGE_ORDER_ERR";

export const GET_EXCHANGE_ORDER_SUCCESS = "GET_EXCHANGE_ORDER_SUCCESS";
export const GET_EXCHANGE_ORDER_ERR = "GET_EXCHANGE_ORDER_ERR";

export const BUY_TOKEN_SUCCESS = "BUY_TOKEN_SUCCESS";
export const BUY_TOKEN_ERR = "BUY_TOKEN_ERR";
export const DELETE_ORDER = "DELETE_ORDER";
export const BUY_TOKENSS = "BUY_TOKENSS";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERR = "UPDATE_ORDER_ERR";
export const GET_SELL_TOKENS = "SELL_TOKEN";
export const VANISH_TOKEN = "VANISH_TOKEN";

//Subscriptions
export const GET_OPEN_SUBSCRIPTION_SUCCESS = "GET_OPEN_SUBSCRIPTION_SUCCESS";
export const GET_OPEN_SUBSCRIPTION_ERR = "GET_OPEN_SUBSCRIPTION_ERR";
export const GET_UPCOMING_SUBSCRIPTION_SUCCESS =
  "GET_UPCOMING_SUBSCRIPTION_SUCCESS";
export const GET_UPCOMING_SUBSCRIPTION_ERR = "GET_UPCOMING_SUBSCRIPTION_ERR";
export const GET_YOUR_SUBSCRIPTION_SUCCESS = "GET_YOUR_SUBSCRIPTION_SUCCESS";
export const GET_YOUR_SUBSCRIPTION_ERR = "GET_YOUR_SUBSCRIPTION_ERR";

export const SUBSCRIPTION_BUY_SUCCESS = "SUBSCRIPTION_BUY_SUCCESS";
export const SUBSCRIPTION_BUY_ERR = "SUBSCRIPTION_BUY_ERR";

//Voting Types
export const GET_ALL_ITO_SUCCESS = "GET_ALL_ITO_SUCCESS";
export const GET_ALL_ITO_ERR = "GET_ALL_ITO_ERR";

export const GET_ONGOING_VOTING_SUCCESS = "GET_ONGOING_VOTING_SUCCESS";
export const GET_ONGOING_VOTING_ERR = "GET_ONGOING_VOTING_ERR";

export const GET_UPCOMING_VOTING_SUCCESS = "GET_UPCOMING_VOTING_SUCCESS";
export const GET_UPCOMING_VOTING_ERR = "GET_UPCOMING_VOTING_ERR";

export const GET_CLOSED_VOTING_SUCCESS = "GET_CLOSED_VOTING_SUCCESS";
export const GET_CLOSED_VOTING_ERR = "GET_CLOSED_VOTING_ERR";

export const GET_VOTING_DETAIL_SUCCESS = "GET_VOTING_DETAIL_SUCCESS";
export const GET_VOTING_DETAIL_ERR = "GET_VOTING_DETAIL_ERR";

export const CREATE_VOTE_SUCCESS = "CREATE_VOTE_SUCCESS";
export const CREATE_VOTE_ERR = "CREATE_VOTE_ERR";

export const CAST_VOTE_SUCCESS = "CAST_VOTE_SUCCESS";
export const CAST_VOTE_ERR = "CAST_VOTE_ERR";

export const GET_VOTE_STATUS_SUCCESS = "GET_VOTE_STATUS_SUCCESS";
export const GET_VOTE_STATUS_ERR = "GET_VOTE_STATUS_ERR";

// Transfer Types
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_ERR = "GET_USERS_LIST_ERR";

//Ito Management Types

//Admin Management Types

//Calculator Types
