export const data = [
  {
    id: 0,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 1,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 2,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 3,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 4,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 5,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 6,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 7,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 8,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 9,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 10,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 11,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 12,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 13,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
  {
    id: 14,
    SubscriptionsName: "Subscriptions Name",
    ITOName: "ITO Name",
    Threshold: "Threshold $30",
    date: "10 Nov 2020 - 31 Jan 2020",
  },
];
