export const data = [
  {
    id: 1,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 2,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 3,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 4,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 5,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 6,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 7,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 8,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 9,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 10,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
  {
    id: 11,
    tokenName: "TCN(Bit)",
    tokenSymbol: "TCN",
    orderType: "Buy Request",
    status: "Completed",
    amount: "55",
  },
];
